export const GET_USER_BY_USERNAME = 'Profile/GET_USER_BY_USERNAME';
export const SET_USER_BY_USERNAME = 'Profile/SET_USER_BY_USERNAME';

export const GET_HISTORY_BY_USERNAME = 'Profile/GET_HISTORY_BY_USERNAME'
export const SET_HISTORY_BY_USERNAME = 'Profile/SET_HISTORY_BY_USERNAME'
