export const FETCH_QUIZ_BY_ID_REQUEST = 'FETCH_QUIZ_BY_ID_REQUEST';
export const FETCH_QUIZ_BY_ID_SUCCESS = 'FETCH_QUIZ_BY_ID_SUCCESS';
export const FETCH_QUIZ_BY_ID_FAILURE = 'FETCH_QUIZ_BY_ID_FAILURE';
  